# Generated by Django 5.2.4 on 2025-07-23 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticdata',
            name='month',
        ),
    ]
