# Generated by Django 5.2.4 on 2025-12-19 06:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('content', models.TextField(verbose_name='To‘liq matn')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'E’lon / Tender',
                'verbose_name_plural': 'E’lonlar / Tenderlar',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='FoydalanuvchiStatistika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jami_kirishlar', models.PositiveIntegerField(default=0)),
                ('oxirgi_faollik', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessiyaIzlovi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessiya_id', models.CharField(max_length=100, unique=True)),
                ('oxirgi_harakat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author_ru',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author_uz',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content_uz',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='ageRange',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='benefits_ru',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='benefits_uz',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='category_uz',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='color',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='salaryRange',
        ),
        migrations.RemoveField(
            model_name='lostitemrequest',
            name='message_ru',
        ),
        migrations.RemoveField(
            model_name='lostitemrequest',
            name='message_uz',
        ),
        migrations.RemoveField(
            model_name='lostitemrequest',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='lostitemrequest',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='news',
            name='likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Muallif'),
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='answered_requests',
            field=models.PositiveIntegerField(default=0, verbose_name='Qabul qilinganlar'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='education_status_en',
            field=models.CharField(blank=True, choices=[('oliy', 'Higher'), ("o'rta", 'Secondary'), ("o'rta mahsus", 'Specialized secondary')], max_length=20, null=True, verbose_name="Ma'lumot (en)"),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='education_status_ru',
            field=models.CharField(blank=True, choices=[('oliy', 'Высшее'), ("o'rta", 'Среднее'), ("o'rta mahsus", 'Среднее специальное')], max_length=20, null=True, verbose_name="Ma'lumot (ru)"),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='education_status_uz',
            field=models.CharField(blank=True, choices=[('oliy', 'Oliy'), ("o'rta", "O'rta"), ("o'rta mahsus", "O'rta mahsus")], max_length=20, null=True, verbose_name="Ma'lumot (uz)"),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='mutaxasislik_en',
            field=models.TextField(blank=True, null=True, verbose_name='Mutaxasislik (en)'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='mutaxasislik_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Мутации (ru)'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='mutaxasislik_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Mutaxasislik (uz)'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='pending_requests',
            field=models.PositiveIntegerField(default=0, verbose_name='Ko‘rib chiqilayotganlar'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='rejected_requests',
            field=models.PositiveIntegerField(default=0, verbose_name='Rad etilganlar'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='requirements_en',
            field=models.TextField(blank=True, null=True, verbose_name='Requirements (en)'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (en)'),
        ),
        migrations.AddField(
            model_name='lostitemrequest',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='lostitemrequest',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Xabar'),
        ),
        migrations.AddField(
            model_name='lostitemrequest',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ism'),
        ),
        migrations.AddField(
            model_name='lostitemrequest',
            name='passport',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Passport'),
        ),
        migrations.AddField(
            model_name='lostitemrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Javob berilmagan'), ('answered', 'Javob berilgan')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='news',
            name='category_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category (en)'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Short description (en)'),
        ),
        migrations.AddField(
            model_name='news',
            name='fullContent_en',
            field=models.TextField(blank=True, null=True, verbose_name='Full text (en)'),
        ),
        migrations.AddField(
            model_name='news',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes soni'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (en)'),
        ),
        migrations.AddField(
            model_name='statisticdata',
            name='year',
            field=models.CharField(choices=[('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], default='2025', max_length=20, verbose_name='Yil / Год / Year'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.news', verbose_name='Yangilik / Новость / News'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('news_editor', 'Yangiliklar muharriri'), ('hr', 'Kadrlar bo‘limi'), ('statistician', 'Statistik'), ('lost_item_support', 'Murojatlar bo‘limi')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan / Кем создано / Created By'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='requirements_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Требования (ru)'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='requirements_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Talablar (uz)'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (ru)'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom (uz)'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория (ru)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategoriya (uz)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание (ru)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Qisqa tavsif (uz)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='fullContent_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Полный текст (ru)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='fullContent_uz',
            field=models.TextField(blank=True, null=True, verbose_name='To‘liq matn (uz)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publishedAt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='E’lon qilingan vaqt / Дата публикации / Published At'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (ru)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sarlavha (uz)'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Rasm / Фото / Image'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.news', verbose_name='Yangilik / Новость / News'),
        ),
        migrations.AlterField(
            model_name='statisticdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqt / Дата добавления / Created At'),
        ),
        migrations.AlterField(
            model_name='statisticdata',
            name='month',
            field=models.CharField(choices=[('Yanvar', 'Yanvar'), ('Fevral', 'Fevral'), ('Mart', 'Mart'), ('Aprel', 'Aprel'), ('May', 'May'), ('Iyun', 'Iyun'), ('Iyul', 'Iyul'), ('Avgust', 'Avgust'), ('Sentyabr', 'Sentyabr'), ('Oktyabr', 'Oktyabr'), ('Noyabr', 'Noyabr'), ('Dekabr', 'Dekabr')], default='Yanvar', max_length=20, verbose_name='Oy / Месяц / Month'),
        ),
        migrations.AlterField(
            model_name='statisticdata',
            name='station_name',
            field=models.CharField(choices=[('Beruniy', 'Beruniy'), ('Tinchlik', 'Tinchlik'), ('Chorsu', 'Chorsu'), ('Gʻafur Gʻulom', 'Gʻafur Gʻulom'), ('Alisher Navoiy', 'Alisher Navoiy'), ('Abdulla Qodiriy', 'Abdulla Qodiriy'), ('Pushkin', 'Pushkin'), ('Buyuk Ipak Yoʻli', 'Buyuk Ipak Yoʻli'), ('Novza', 'Novza'), ('Milliy bogʻ', 'Milliy bogʻ'), ('Xalqlar doʻstligi', 'Xalqlar doʻstligi'), ('Chilonzor', 'Chilonzor'), ('Mirzo Ulugʻbek', 'Mirzo Ulugʻbek'), ('Olmazor', 'Olmazor'), ('Doʻstlik', 'Doʻstlik'), ('Mashinasozlar', 'Mashinasozlar'), ('Toshkent', 'Toshkent'), ('Oybek', 'Oybek'), ('Kosmonavtlar', 'Kosmonavtlar'), ('Oʻzbekiston', 'Oʻzbekiston'), ('Hamid Olimjon', 'Hamid Olimjon'), ('Mingoʻrik', 'Mingoʻrik'), ('Yunus Rajabiy', 'Yunus Rajabiy'), ('Shahriston', 'Shahriston'), ('Bodomzor', 'Bodomzor'), ('Minor', 'Minor'), ('Turkiston', 'Turkiston'), ('Yunusobod', 'Yunusobod'), ('Tuzel', 'Tuzel'), ('Yashnobod', 'Yashnobod'), ('Texnopark', 'Texnopark'), ('Sergeli', 'Sergeli'), ('Choshtepa', 'Choshtepa'), ('Turon', 'Turon'), ('Chinor', 'Chinor'), ('Yangiobod', 'Yangiobod'), ('Rohat', 'Rohat'), ('Oʻzgarish', 'Oʻzgarish'), ('Yangihayot', 'Yangihayot'), ('Qoʻyliq', 'Qoʻyliq'), ('Matonat', 'Matonat'), ('Qiyot', 'Qiyot'), ('Tolariq', 'Tolariq'), ('Xonobod', 'Xonobod'), ('Quruvchilar', 'Quruvchilar'), ('Olmos', 'Olmos'), ('Paxtakor', 'Paxtakor'), ('Qipchoq', 'Qipchoq'), ('Amir Temur xiyoboni', 'Amir Temur xiyoboni'), ('Mustaqillik maydoni', 'Mustaqillik maydoni')], max_length=100, verbose_name='Bekat / Станция / Station'),
        ),
        migrations.AlterField(
            model_name='statisticdata',
            name='user_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Foydalanuvchilar soni / Кол-во пользователей / Users Count'),
        ),
        migrations.CreateModel(
            name='AnnouncementComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Muallif')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='announcements/', verbose_name='Rasm')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='JobVacancyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ism (uz)')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('file', models.FileField(blank=True, null=True, upload_to='jobVacancyRequests/', verbose_name='Fayl')),
                ('status', models.CharField(choices=[('pending', "Ko'rilmoqda"), ('answered', 'Javob berilgan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqt')),
                ('jobVacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='home.jobvacancy', verbose_name='Vakansiya')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='home.announcement')),
            ],
            options={
                'verbose_name': 'E’lon like',
                'verbose_name_plural': 'E’lon like-lar',
                'unique_together': {('announcement', 'session_key')},
            },
        ),
        migrations.CreateModel(
            name='NewsLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='home.news')),
            ],
            options={
                'verbose_name': 'News Like',
                'verbose_name_plural': 'News Likes',
                'unique_together': {('news', 'session_key')},
            },
        ),
    ]
