# Generated by Django 5.2.4 on 2026-01-15 08:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], db_index=True, default='uz', max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FoydalanuvchiStatistika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jami_kirishlar', models.PositiveIntegerField(default=0)),
                ('oxirgi_faollik', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Korrupsiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('uz', 'Uz'), ('ru', 'Ru'), ('en', 'En')], default='uz', max_length=2, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Qisqa tavsif')),
                ('fullContent', models.TextField(blank=True, null=True, verbose_name='To‘liq matn')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategoriya')),
                ('publishedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('like_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SessiyaIzlovi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessiya_id', models.CharField(max_length=100, unique=True)),
                ('oxirgi_harakat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=50, verbose_name='Familiya')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefon')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author_ru',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author_uz',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content_uz',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='ageRange',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='benefits_ru',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='benefits_uz',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='category_uz',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='color',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='requirements_ru',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='requirements_uz',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='salaryRange',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='lostitemrequest',
            name='message_ru',
        ),
        migrations.RemoveField(
            model_name='lostitemrequest',
            name='message_uz',
        ),
        migrations.RemoveField(
            model_name='lostitemrequest',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='lostitemrequest',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='news',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='category_uz',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='news',
            name='fullContent_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='fullContent_uz',
        ),
        migrations.RemoveField(
            model_name='news',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_uz',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Muallif'),
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='answered_requests',
            field=models.PositiveIntegerField(default=0, verbose_name='Qabul qilinganlar'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='education_status',
            field=models.CharField(blank=True, choices=[('oliy', 'Oliy/Высшее'), ('o-rta', "O'rta/Среднее"), ('o-rta-mahsus', "O'rta mahsus")], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='language',
            field=models.CharField(blank=True, choices=[('uz', 'Uz'), ('ru', 'Ru'), ('en', 'En')], default='uz', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='mutaxasislik',
            field=models.TextField(blank=True, null=True, verbose_name='Mutaxasislik'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='pending_requests',
            field=models.PositiveIntegerField(default=0, verbose_name='Ko‘rib chiqilayotganlar'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='rejected_requests',
            field=models.PositiveIntegerField(default=0, verbose_name='Rad etilganlar'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Talablar'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='lostitemrequest',
            name='address',
            field=models.CharField(default=1, max_length=255, verbose_name='Manzil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostitemrequest',
            name='message',
            field=models.TextField(default=1, verbose_name='Xabar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostitemrequest',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Ism'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostitemrequest',
            name='passport',
            field=models.CharField(default=1, max_length=9, verbose_name='Passport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostitemrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Javob berilmagan'), ('answered', 'Javob berilgan')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='news',
            name='fullContent',
            field=models.TextField(blank=True, null=True, verbose_name='To‘liq matn'),
        ),
        migrations.AddField(
            model_name='news',
            name='language',
            field=models.CharField(blank=True, choices=[('uz', 'Uz'), ('ru', 'Ru'), ('en', 'En')], default='uz', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='statisticdata',
            name='year',
            field=models.CharField(choices=[('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], default='2025', max_length=20, verbose_name='Yil / Год / Year'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.news', verbose_name='Yangilik / Новость / News'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('news_editor', 'Yangiliklar muharriri'), ('hr', 'Kadrlar bo‘limi'), ('statistician', 'Statistik'), ('lost_item_support', 'Murojatlar bo‘limi'), ('simple', 'Simple User')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Rasm / Фото / Image'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.news', verbose_name='Yangilik / Новость / News'),
        ),
        migrations.AlterField(
            model_name='statisticdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqt / Дата добавления / Created At'),
        ),
        migrations.AlterField(
            model_name='statisticdata',
            name='month',
            field=models.CharField(choices=[('Yanvar', 'Yanvar'), ('Fevral', 'Fevral'), ('Mart', 'Mart'), ('Aprel', 'Aprel'), ('May', 'May'), ('Iyun', 'Iyun'), ('Iyul', 'Iyul'), ('Avgust', 'Avgust'), ('Sentyabr', 'Sentyabr'), ('Oktyabr', 'Oktyabr'), ('Noyabr', 'Noyabr'), ('Dekabr', 'Dekabr')], default='Yanvar', max_length=20, verbose_name='Oy / Месяц / Month'),
        ),
        migrations.AlterField(
            model_name='statisticdata',
            name='station_name',
            field=models.CharField(choices=[('Beruniy', 'Beruniy'), ('Tinchlik', 'Tinchlik'), ('Chorsu', 'Chorsu'), ('Gʻafur Gʻulom', 'Gʻafur Gʻulom'), ('Alisher Navoiy', 'Alisher Navoiy'), ('Abdulla Qodiriy', 'Abdulla Qodiriy'), ('Pushkin', 'Pushkin'), ('Buyuk Ipak Yoʻli', 'Buyuk Ipak Yoʻli'), ('Novza', 'Novza'), ('Milliy bogʻ', 'Milliy bogʻ'), ('Xalqlar doʻstligi', 'Xalqlar doʻstligi'), ('Chilonzor', 'Chilonzor'), ('Mirzo Ulugʻbek', 'Mirzo Ulugʻbek'), ('Olmazor', 'Olmazor'), ('Doʻstlik', 'Doʻstlik'), ('Mashinasozlar', 'Mashinasozlar'), ('Toshkent', 'Toshkent'), ('Oybek', 'Oybek'), ('Kosmonavtlar', 'Kosmonavtlar'), ('Oʻzbekiston', 'Oʻzbekiston'), ('Hamid Olimjon', 'Hamid Olimjon'), ('Mingoʻrik', 'Mingoʻrik'), ('Yunus Rajabiy', 'Yunus Rajabiy'), ('Shahriston', 'Shahriston'), ('Bodomzor', 'Bodomzor'), ('Minor', 'Minor'), ('Turkiston', 'Turkiston'), ('Yunusobod', 'Yunusobod'), ('Tuzel', 'Tuzel'), ('Yashnobod', 'Yashnobod'), ('Texnopark', 'Texnopark'), ('Sergeli', 'Sergeli'), ('Choshtepa', 'Choshtepa'), ('Turon', 'Turon'), ('Chinor', 'Chinor'), ('Yangiobod', 'Yangiobod'), ('Rohat', 'Rohat'), ('Oʻzgarish', 'Oʻzgarish'), ('Yangihayot', 'Yangihayot'), ('Qoʻyliq', 'Qoʻyliq'), ('Matonat', 'Matonat'), ('Qiyot', 'Qiyot'), ('Tolariq', 'Tolariq'), ('Xonobod', 'Xonobod'), ('Quruvchilar', 'Quruvchilar'), ('Olmos', 'Olmos'), ('Paxtakor', 'Paxtakor'), ('Qipchoq', 'Qipchoq'), ('Amir Temur xiyoboni', 'Amir Temur xiyoboni'), ('Mustaqillik maydoni', 'Mustaqillik maydoni')], max_length=100, verbose_name='Bekat / Станция / Station'),
        ),
        migrations.AlterField(
            model_name='statisticdata',
            name='user_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Foydalanuvchilar soni / Кол-во пользователей / Users Count'),
        ),
        migrations.CreateModel(
            name='AnnouncementComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Muallif')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='announcements/', verbose_name='Rasm')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='JobVacancyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ism (uz)')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('file', models.FileField(blank=True, null=True, upload_to='jobVacancyRequests/', verbose_name='Fayl')),
                ('status', models.CharField(choices=[('pending', "Ko'rilmoqda"), ('answered', 'Javob berilgan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqt')),
                ('jobVacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='home.jobvacancy', verbose_name='Vakansiya')),
            ],
        ),
        migrations.CreateModel(
            name='KorrupsiyaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Muallif')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('korrupsiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.korrupsiya', verbose_name='Korrupsiya yangiliklari')),
            ],
        ),
        migrations.CreateModel(
            name='KorrupsiyaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='korrupsiya_images/', verbose_name='Rasm')),
                ('korrupsiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.korrupsiya', verbose_name='Korrupsiya yangiliklari')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.simpleuser')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='home.announcement')),
            ],
            options={
                'verbose_name': 'E’lon like',
                'verbose_name_plural': 'E’lon like-lar',
                'unique_together': {('announcement', 'session_key')},
            },
        ),
        migrations.CreateModel(
            name='KorrupsiyaLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('korrupsiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='home.korrupsiya')),
            ],
            options={
                'verbose_name': 'Korrupsiya Like',
                'verbose_name_plural': 'Korrupsiya Likes',
                'unique_together': {('korrupsiya', 'session_key')},
            },
        ),
        migrations.CreateModel(
            name='NewsLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='home.news')),
            ],
            options={
                'verbose_name': 'News Like',
                'verbose_name_plural': 'News Likes',
                'unique_together': {('news', 'session_key')},
            },
        ),
        migrations.CreateModel(
            name='NewsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='home.news')),
            ],
            options={
                'verbose_name': 'News View',
                'verbose_name_plural': 'News Views',
                'unique_together': {('news', 'session_key')},
            },
        ),
    ]
