# Generated by Django 5.2.4 on 2026-01-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_announcement_foydalanuvchistatistika_korrupsiya_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='korrupsiya',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
