# Generated by Django 5.2.4 on 2026-01-16 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_korrupsiya_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='home.announcement')),
            ],
            options={
                'unique_together': {('announcement', 'session_key')},
            },
        ),
        migrations.CreateModel(
            name='KorrupsiyaView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('korrupsiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='home.korrupsiya')),
            ],
            options={
                'unique_together': {('korrupsiya', 'session_key')},
            },
        ),
    ]
