# Generated by Django 5.2.4 on 2025-07-24 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_statisticdata_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobvacancy',
            name='color',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='icon',
        ),
    ]
