# Generated by Django 5.2.4 on 2025-12-19 09:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_announcement_options_announcement_lang_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='education_status_en',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='education_status_ru',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='education_status_uz',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='mutaxasislik_en',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='mutaxasislik_ru',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='mutaxasislik_uz',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='requirements_en',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='requirements_ru',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='requirements_uz',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='news',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='category_uz',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='news',
            name='fullContent_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='fullContent_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='fullContent_uz',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_uz',
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='education_status',
            field=models.CharField(blank=True, choices=[('oliy', 'Oliy/Высшее'), ('o-rta', "O'rta/Среднее"), ('o-rta-mahsus', "O'rta mahsus")], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='language',
            field=models.CharField(blank=True, choices=[('uz', 'Uz'), ('ru', 'Ru'), ('en', 'En')], default='uz', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='mutaxasislik',
            field=models.TextField(blank=True, null=True, verbose_name='Mutaxasislik'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Talablar'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='news',
            name='fullContent',
            field=models.TextField(blank=True, null=True, verbose_name='To‘liq matn'),
        ),
        migrations.AddField(
            model_name='news',
            name='language',
            field=models.CharField(blank=True, choices=[('uz', 'Uz'), ('ru', 'Ru'), ('en', 'En')], default='uz', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='publishedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
