# Generated by Django 5.2.4 on 2025-07-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_jobvacancy_color_remove_jobvacancy_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='benefits_ru',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='benefits_uz',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='requirements_ru',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='requirements_uz',
            field=models.TextField(),
        ),
    ]
