# Generated by Django 5.2.4 on 2025-12-23 03:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_news_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korrupsiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('uz', 'Uz'), ('ru', 'Ru'), ('en', 'En')], default='uz', max_length=2, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Qisqa tavsif')),
                ('fullContent', models.TextField(blank=True, null=True, verbose_name='To‘liq matn')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategoriya')),
                ('publishedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('like_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KorrupsiyaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Muallif')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('korrupsiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.korrupsiya', verbose_name='Korrupsiya yangiliklari')),
            ],
        ),
        migrations.CreateModel(
            name='KorrupsiyaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='korrupsiya_images/', verbose_name='Rasm')),
                ('korrupsiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.korrupsiya', verbose_name='Korrupsiya yangiliklari')),
            ],
        ),
        migrations.CreateModel(
            name='KorrupsiyaLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('korrupsiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='home.korrupsiya')),
            ],
            options={
                'verbose_name': 'Korrupsiya Like',
                'verbose_name_plural': 'Korrupsiya Likes',
                'unique_together': {('korrupsiya', 'session_key')},
            },
        ),
    ]
