# Generated by Django 5.2.4 on 2026-01-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_announcementview_korrupsiyaview'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mediateka/photos/')),
                ('title_key', models.CharField(default='photon_view', help_text='i18n key (masalan: photon_view)', max_length=100)),
                ('category_key', models.CharField(default='metro', help_text='i18n key (masalan: metro)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MediaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(help_text='YouTube embed URL (https://www.youtube.com/embed/...)')),
                ('thumbnail', models.ImageField(upload_to='mediateka/videos/thumbnails/')),
                ('title_key', models.CharField(help_text='i18n key (masalan: mysterious_corridors)', max_length=100)),
                ('duration', models.CharField(help_text='Masalan: 15:42', max_length=20)),
                ('views', models.CharField(help_text='Masalan: 125K', max_length=20)),
                ('category_key', models.CharField(default='metropolitan', help_text='i18n key (masalan: metropolitan)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
