# Generated by Django 5.2.4 on 2025-07-25 03:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_jobvacancy_benefits_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobvacancy',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='category_uz',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='salaryRange',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_ru',
            field=models.CharField(max_length=100, verbose_name='Muallif (ru)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_uz',
            field=models.CharField(max_length=100, verbose_name='Muallif (uz)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_ru',
            field=models.TextField(verbose_name='Izoh (ru)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_uz',
            field=models.TextField(verbose_name='Izoh (uz)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.news', verbose_name='Yangilik'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('news_editor', 'Yangiliklar muharriri'), ('hr', 'Kadrlar bo‘limi'), ('statistician', 'Statistik'), ('lost_item_support', 'Murojatlar bo‘limi')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='ageRange',
            field=models.CharField(max_length=50, verbose_name='Yosh oralig‘i'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='benefits_ru',
            field=models.TextField(verbose_name='Imtiyozlar (ru)'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='benefits_uz',
            field=models.TextField(verbose_name='Imtiyozlar (uz)'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan yaratilgan'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='requirements_ru',
            field=models.TextField(verbose_name='Talablar (ru)'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='requirements_uz',
            field=models.TextField(verbose_name='Talablar (uz)'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name='Nom (ru)'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='title_uz',
            field=models.CharField(max_length=255, verbose_name='Nom (uz)'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='message_ru',
            field=models.TextField(verbose_name='Xabar (ru)'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='message_uz',
            field=models.TextField(verbose_name='Xabar (uz)'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='name_ru',
            field=models.CharField(max_length=100, verbose_name='Ism (ru)'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='name_uz',
            field=models.CharField(max_length=100, verbose_name='Ism (uz)'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category_ru',
            field=models.CharField(max_length=100, verbose_name='Kategoriya (ru)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category_uz',
            field=models.CharField(max_length=100, verbose_name='Kategoriya (uz)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ru',
            field=models.TextField(verbose_name='Qisqa tavsif (ru)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_uz',
            field=models.TextField(verbose_name='Qisqa tavsif (uz)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='fullContent_ru',
            field=models.TextField(verbose_name='To‘liq matn (ru)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='fullContent_uz',
            field=models.TextField(verbose_name='To‘liq matn (uz)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_news', to=settings.AUTH_USER_MODEL, verbose_name='Layklar'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publishedAt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='E’lon qilingan vaqt'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name='Sarlavha (ru)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=255, verbose_name='Sarlavha (uz)'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.news', verbose_name='Yangilik'),
        ),
        migrations.AlterField(
            model_name='statisticdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='statisticdata',
            name='month',
            field=models.CharField(choices=[('Yanvar', 'Yanvar'), ('Fevral', 'Fevral'), ('Mart', 'Mart'), ('Aprel', 'Aprel'), ('May', 'May'), ('Iyun', 'Iyun'), ('Iyul', 'Iyul'), ('Avgust', 'Avgust'), ('Sentyabr', 'Sentyabr'), ('Oktyabr', 'Oktyabr'), ('Noyabr', 'Noyabr'), ('Dekabr', 'Dekabr')], default='Yanvar', max_length=20, verbose_name='Oy'),
        ),
        migrations.AlterField(
            model_name='statisticdata',
            name='station_name',
            field=models.CharField(choices=[('Beruniy', 'Beruniy'), ('Tinchlik', 'Tinchlik'), ('Chorsu', 'Chorsu'), ('Gʻafur Gʻulom', 'Gʻafur Gʻulom'), ('Alisher Navoiy', 'Alisher Navoiy'), ('Abdulla Qodiriy', 'Abdulla Qodiriy'), ('Pushkin', 'Pushkin'), ('Buyuk Ipak Yoʻli', 'Buyuk Ipak Yoʻli'), ('Novza', 'Novza'), ('Milliy bogʻ', 'Milliy bogʻ'), ('Xalqlar doʻstligi', 'Xalqlar doʻstligi'), ('Chilonzor', 'Chilonzor'), ('Mirzo Ulugʻbek', 'Mirzo Ulugʻbek'), ('Olmazor', 'Olmazor'), ('Doʻstlik', 'Doʻstlik'), ('Mashinasozlar', 'Mashinasozlar'), ('Toshkent', 'Toshkent'), ('Oybek', 'Oybek'), ('Kosmonavtlar', 'Kosmonavtlar'), ('Oʻzbekiston', 'Oʻzbekiston'), ('Hamid Olimjon', 'Hamid Olimjon'), ('Ming Oʻrik', 'Ming Oʻrik'), ('Yunus Rajabiy', 'Yunus Rajabiy'), ('Shahriston', 'Shahriston'), ('Bodomzor', 'Bodomzor'), ('Minor', 'Minor'), ('Turkiston', 'Turkiston'), ('Yunusobod', 'Yunusobod'), ('Tuzel', 'Tuzel'), ('Yashnobod', 'Yashnobod'), ('Texnopark', 'Texnopark'), ('Doʻstlik-2', 'Doʻstlik-2'), ('Sergeli', 'Sergeli'), ('Afrosiyob', 'Afrosiyob'), ('Choshtepa', 'Choshtepa'), ('Turon', 'Turon'), ('Chinor', 'Chinor'), ('Yangiobod', 'Yangiobod'), ('Rohat', 'Rohat'), ('Oʻzgarish', 'Oʻzgarish'), ('Yangihayot', 'Yangihayot'), ('Qoʻyliq', 'Qoʻyliq'), ('Matonat', 'Matonat'), ('Qiyot', 'Qiyot'), ('Tolariq', 'Tolariq'), ('Xonobod', 'Xonobod'), ('Quruvchilar', 'Quruvchilar'), ('Olmos', 'Olmos'), ('Amir Temur xiyoboni', 'Amir Temur xiyoboni'), ('Mustaqillik maydoni', 'Mustaqillik maydoni')], max_length=100, verbose_name='Bekat nomi'),
        ),
        migrations.AlterField(
            model_name='statisticdata',
            name='user_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Foydalanuvchilar soni'),
        ),
    ]
