# Generated by Django 5.2.4 on 2025-12-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_korrupsiya_korrupsiyacomment_korrupsiyaimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitemrequest',
            name='address',
            field=models.CharField(default=1, max_length=255, verbose_name='Manzil'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='message',
            field=models.TextField(default=1, verbose_name='Xabar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Ism'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='passport',
            field=models.CharField(default=1, max_length=9, verbose_name='Passport'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='phone',
            field=models.CharField(default=1, max_length=20, verbose_name='Telefon'),
            preserve_default=False,
        ),
    ]
