# Generated by Django 5.2.4 on 2026-01-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_mediaphoto_mediavideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(help_text='Bo‘lim nomi (masalan: main_page, navbar, footer)', max_length=100)),
                ('image', models.ImageField(upload_to='frontend_images/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
    ]
