# Generated by Django 5.2.4 on 2026-01-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_frontendimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediavideo',
            name='views',
            field=models.CharField(editable=False, help_text='Avtomatik tarzda jami foydalanuvchilar soni bilan to‘ldiriladi', max_length=20),
        ),
    ]
