# Generated by Django 5.2.4 on 2025-07-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_jobvacancy_category_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoydalanuvchiStatistika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jami_kirishlar', models.PositiveIntegerField(default=0, verbose_name='Jami kirishlar soni')),
                ('oxirgi_faollik', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilanish vaqti')),
            ],
        ),
        migrations.CreateModel(
            name='SessiyaIzlovi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessiya_id', models.CharField(max_length=100, unique=True)),
                ('oxirgi_harakat', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
