# Generated by Django 5.2.4 on 2026-01-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_simpleuser_phoneverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('news_editor', 'Yangiliklar muharriri'), ('hr', 'Kadrlar bo‘limi'), ('statistician', 'Statistik'), ('lost_item_support', 'Murojatlar bo‘limi'), ('simple', 'Simple User')], max_length=30, null=True),
        ),
    ]
