# Generated by Django 5.2.4 on 2026-01-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_mediavideo_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Bekat nomi')),
                ('image1', models.ImageField(upload_to='stations/', verbose_name='Rasm 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='stations/', verbose_name='Rasm 2')),
                ('video_title', models.CharField(max_length=255, verbose_name='Video sarlavhasi')),
                ('video_url', models.URLField(verbose_name='Video Linki (Embed)')),
                ('video_thumbnail', models.URLField(verbose_name='Video muqovasi (URL)')),
            ],
            options={
                'verbose_name': "Bekat ma'lumoti",
                'verbose_name_plural': "Bekat ma'lumotlari",
            },
        ),
    ]
