# Generated by Django 5.2.4 on 2025-07-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_foydalanuvchistatistika_sessiyaizlovi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticdata',
            name='station_name',
            field=models.CharField(choices=[('Beruniy', 'Beruniy'), ('Tinchlik', 'Tinchlik'), ('Chorsu', 'Chorsu'), ('Gʻafur Gʻulom', 'Gʻafur Gʻulom'), ('Alisher Navoiy', 'Alisher Navoiy'), ('Abdulla Qodiriy', 'Abdulla Qodiriy'), ('Pushkin', 'Pushkin'), ('Buyuk Ipak Yoʻli', 'Buyuk Ipak Yoʻli'), ('Novza', 'Novza'), ('Milliy bogʻ', 'Milliy bogʻ'), ('Xalqlar doʻstligi', 'Xalqlar doʻstligi'), ('Chilonzor', 'Chilonzor'), ('Mirzo Ulugʻbek', 'Mirzo Ulugʻbek'), ('Olmazor', 'Olmazor'), ('Doʻstlik', 'Doʻstlik'), ('Mashinasozlar', 'Mashinasozlar'), ('Toshkent', 'Toshkent'), ('Oybek', 'Oybek'), ('Kosmonavtlar', 'Kosmonavtlar'), ('Oʻzbekiston', 'Oʻzbekiston'), ('Hamid Olimjon', 'Hamid Olimjon'), ('Ming Oʻrik', 'Ming Oʻrik'), ('Yunus Rajabiy', 'Yunus Rajabiy'), ('Shahriston', 'Shahriston'), ('Bodomzor', 'Bodomzor'), ('Minor', 'Minor'), ('Turkiston', 'Turkiston'), ('Yunusobod', 'Yunusobod'), ('Tuzel', 'Tuzel'), ('Yashnobod', 'Yashnobod'), ('Texnopark', 'Texnopark'), ('Doʻstlik-2', 'Doʻstlik-2'), ('Sergeli', 'Sergeli'), ('Choshtepa', 'Choshtepa'), ('Turon', 'Turon'), ('Chinor', 'Chinor'), ('Yangiobod', 'Yangiobod'), ('Rohat', 'Rohat'), ('Oʻzgarish', 'Oʻzgarish'), ('Yangihayot', 'Yangihayot'), ('Qoʻyliq', 'Qoʻyliq'), ('Matonat', 'Matonat'), ('Qiyot', 'Qiyot'), ('Tolariq', 'Tolariq'), ('Xonobod', 'Xonobod'), ('Quruvchilar', 'Quruvchilar'), ('Olmos', 'Olmos'), ('Amir Temur xiyoboni', 'Amir Temur xiyoboni'), ('Mustaqillik maydoni', 'Mustaqillik maydoni')], max_length=100, verbose_name='Bekat nomi'),
        ),
    ]
