# Generated by Django 5.2.4 on 2026-01-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_stationfront'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationfront',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='stations/video_thumbnails/', verbose_name='Video muqovasi (Fayl)'),
        ),
    ]
