# Generated by Django 5.2.4 on 2025-07-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_statisticdata_station_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Muallif (en)'),
        ),
        migrations.AddField(
            model_name='comment',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh (en)'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='benefits_en',
            field=models.TextField(blank=True, null=True, verbose_name='Imtiyozlar (en)'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='requirements_en',
            field=models.TextField(blank=True, null=True, verbose_name='Talablar (en)'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom (en)'),
        ),
        migrations.AddField(
            model_name='lostitemrequest',
            name='message_en',
            field=models.TextField(blank=True, null=True, verbose_name='Xabar (en)'),
        ),
        migrations.AddField(
            model_name='lostitemrequest',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ism (en)'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategoriya (en)'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Qisqa tavsif (en)'),
        ),
        migrations.AddField(
            model_name='news',
            name='fullContent_en',
            field=models.TextField(blank=True, null=True, verbose_name='To‘liq matn (en)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sarlavha (en)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Muallif (ru)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Muallif (uz)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh (ru)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh (uz)'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='ageRange',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Yosh oralig‘i'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='benefits_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Imtiyozlar (ru)'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='benefits_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Imtiyozlar (uz)'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='requirements_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Talablar (ru)'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='requirements_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Talablar (uz)'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom (ru)'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom (uz)'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='message_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Xabar (ru)'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='message_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Xabar (uz)'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ism (ru)'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ism (uz)'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategoriya (ru)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategoriya (uz)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Qisqa tavsif (ru)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Qisqa tavsif (uz)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='fullContent_ru',
            field=models.TextField(blank=True, null=True, verbose_name='To‘liq matn (ru)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='fullContent_uz',
            field=models.TextField(blank=True, null=True, verbose_name='To‘liq matn (uz)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sarlavha (ru)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sarlavha (uz)'),
        ),
        migrations.AlterField(
            model_name='statisticdata',
            name='month',
            field=models.CharField(choices=[('Yanvar', [('uz', 'Yanvar'), ('ru', 'Январь'), ('en', 'January')]), ('Fevral', [('uz', 'Fevral'), ('ru', 'Февраль'), ('en', 'February')]), ('Mart', [('uz', 'Mart'), ('ru', 'Март'), ('en', 'March')]), ('Aprel', [('uz', 'Aprel'), ('ru', 'Апрель'), ('en', 'April')]), ('May', [('uz', 'May'), ('ru', 'Май'), ('en', 'May')]), ('Iyun', [('uz', 'Iyun'), ('ru', 'Июнь'), ('en', 'June')]), ('Iyul', [('uz', 'Iyul'), ('ru', 'Июль'), ('en', 'July')]), ('Avgust', [('uz', 'Avgust'), ('ru', 'Август'), ('en', 'August')]), ('Sentyabr', [('uz', 'Sentyabr'), ('ru', 'Сентябрь'), ('en', 'September')]), ('Oktyabr', [('uz', 'Oktyabr'), ('ru', 'Октябрь'), ('en', 'October')]), ('Noyabr', [('uz', 'Noyabr'), ('ru', 'Ноябрь'), ('en', 'November')]), ('Dekabr', [('uz', 'Dekabr'), ('ru', 'Декабрь'), ('en', 'December')])], default='Yanvar', max_length=20, verbose_name='Oy'),
        ),
        migrations.AlterField(
            model_name='statisticdata',
            name='station_name',
            field=models.CharField(choices=[('Beruniy', [('uz', 'Beruniy'), ('ru', 'Беруни'), ('en', 'Beruniy')]), ('Tinchlik', [('uz', 'Tinchlik'), ('ru', 'Тинчлик'), ('en', 'Tinchlik')]), ('Chorsu', [('uz', 'Chorsu'), ('ru', 'Чорсу'), ('en', 'Chorsu')]), ('Gʻafur Gʻulom', [('uz', 'Gʻafur Gʻulom'), ('ru', 'Ғафур Ғулом'), ('en', "G'afur G'ulom")]), ('Alisher Navoiy', [('uz', 'Alisher Navoiy'), ('ru', 'Алишер Навоий'), ('en', 'Alisher Navoiy')]), ('Abdulla Qodiriy', [('uz', 'Abdulla Qodiriy'), ('ru', 'Абдулла Қодирий'), ('en', 'Abdulla Qodiriy')]), ('Pushkin', [('uz', 'Pushkin'), ('ru', 'Пушкин'), ('en', 'Pushkin')]), ('Buyuk Ipak Yoʻli', [('uz', 'Buyuk Ipak Yoʻli'), ('ru', 'Буюк Ипак Йўли'), ('en', 'Buyuk Ipak Yoʻli')]), ('Novza', [('uz', 'Novza'), ('ru', 'Новза'), ('en', 'Novza')]), ('Milliy bogʻ', [('uz', 'Milliy bogʻ'), ('ru', 'Миллий боғ'), ('en', 'Milliy bogʻ')]), ('Xalqlar doʻstligi', [('uz', 'Xalqlar doʻstligi'), ('ru', 'Халқлар дўстлиги'), ('en', 'Xalqlar doʻstligi')]), ('Chilonzor', [('uz', 'Chilonzor'), ('ru', 'Чилонзор'), ('en', 'Chilonzor')]), ('Mirzo Ulugʻbek', [('uz', 'Mirzo Ulugʻbek'), ('ru', 'Мирзо Улуғбек'), ('en', 'Mirzo Ulugʻbek')]), ('Olmazor', [('uz', 'Olmazor'), ('ru', 'Олмазор'), ('en', 'Olmazor')]), ('Doʻstlik', [('uz', 'Doʻstlik'), ('ru', 'Дўстлик'), ('en', 'Doʻstlik')]), ('Mashinasozlar', [('uz', 'Mashinasozlar'), ('ru', 'Машинасозлар'), ('en', 'Mashinasozlar')]), ('Toshkent', [('uz', 'Toshkent'), ('ru', 'Тошкент'), ('en', 'Toshkent')]), ('Oybek', [('uz', 'Oybek'), ('ru', 'Ойбек'), ('en', 'Oybek')]), ('Kosmonavtlar', [('uz', 'Kosmonavtlar'), ('ru', 'Космонавтлар'), ('en', 'Kosmonavtlar')]), ('Oʻzbekiston', [('uz', 'Oʻzbekiston'), ('ru', 'Ўзбекистон'), ('en', 'Oʻzbekiston')]), ('Hamid Olimjon', [('uz', 'Hamid Olimjon'), ('ru', 'Ҳамид Олимжон'), ('en', 'Hamid Olimjon')]), ('Ming Oʻrik', [('uz', 'Ming Oʻrik'), ('ru', 'Минг Ўрик'), ('en', 'Ming Oʻrik')]), ('Yunus Rajabiy', [('uz', 'Yunus Rajabiy'), ('ru', 'Юнус Раджабий'), ('en', 'Yunus Rajabiy')]), ('Shahriston', [('uz', 'Shahriston'), ('ru', 'Шахристон'), ('en', 'Shahriston')]), ('Bodomzor', [('uz', 'Bodomzor'), ('ru', 'Бодомзор'), ('en', 'Bodomzor')]), ('Minor', [('uz', 'Minor'), ('ru', 'Минор'), ('en', 'Minor')]), ('Turkiston', [('uz', 'Turkiston'), ('ru', 'Туркистон'), ('en', 'Turkiston')]), ('Yunusobod', [('uz', 'Yunusobod'), ('ru', 'Юнусобод'), ('en', 'Yunusobod')]), ('Tuzel', [('uz', 'Tuzel'), ('ru', 'Тузел'), ('en', 'Tuzel')]), ('Yashnobod', [('uz', 'Yashnobod'), ('ru', 'Яшнобод'), ('en', 'Yashnobod')]), ('Texnopark', [('uz', 'Texnopark'), ('ru', 'Технопарк'), ('en', 'Texnopark')]), ('Sergeli', [('uz', 'Sergeli'), ('ru', 'Сергели'), ('en', 'Sergeli')]), ('Choshtepa', [('uz', 'Choshtepa'), ('ru', 'Чоштепа'), ('en', 'Choshtepa')]), ('Turon', [('uz', 'Turon'), ('ru', 'Турон'), ('en', 'Turon')]), ('Chinor', [('uz', 'Chinor'), ('ru', 'Чинор'), ('en', 'Chinor')]), ('Yangiobod', [('uz', 'Yangiobod'), ('ru', 'Янгиобод'), ('en', 'Yangiobod')]), ('Rohat', [('uz', 'Rohat'), ('ru', 'Роҳат'), ('en', 'Rohat')]), ('Oʻzgarish', [('uz', 'Oʻzgarish'), ('ru', 'Ўзгариш'), ('en', 'Oʻzgarish')]), ('Yangihayot', [('uz', 'Yangihayot'), ('ru', 'Янгихаёт'), ('en', 'Yangihayot')]), ('Qoʻyliq', [('uz', 'Qoʻyliq'), ('ru', 'Қўйлиқ'), ('en', 'Qoʻyliq')]), ('Matonat', [('uz', 'Matonat'), ('ru', 'Матонат'), ('en', 'Matonat')]), ('Qiyot', [('uz', 'Qiyot'), ('ru', 'Қиёt'), ('en', 'Qiyot')]), ('Tolariq', [('uz', 'Tolariq'), ('ru', 'Толарик'), ('en', 'Tolariq')]), ('Xonobod', [('uz', 'Xonobod'), ('ru', 'Хонобод'), ('en', 'Xonobod')]), ('Quruvchilar', [('uz', 'Quruvchilar'), ('ru', 'Қурувчилар'), ('en', 'Quruvchilar')]), ('Olmos', [('uz', 'Olmos'), ('ru', 'Олмос'), ('en', 'Olmos')]), ('Paxtakor', [('uz', 'Paxtakor'), ('ru', 'Пахтакор'), ('en', 'Paxtakor')]), ('Qipchoq', [('uz', 'Qipchoq'), ('ru', 'Қипчоқ'), ('en', 'Qipchoq')]), ('Amir Temur xiyoboni', [('uz', 'Amir Temur xiyoboni'), ('ru', 'Амир Темур хиёбони'), ('en', 'Amir Temur xiyoboni')]), ('Mustaqillik maydoni', [('uz', 'Mustaqillik maydoni'), ('ru', 'Мустақиллик майдони'), ('en', 'Mustaqillik maydoni')])], max_length=100, verbose_name='Bekat nomi'),
        ),
    ]
