# Generated by Django 5.2.4 on 2026-01-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_stationfront_video_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', 'Uz'), ('ru', 'Ru'), ('en', 'En')], default='uz', max_length=2, verbose_name='Til')),
                ('group_id', models.PositiveIntegerField(verbose_name='Guruh ID (Bir xil rahbarlar uchun bir xil raqam)')),
                ('firstName', models.CharField(max_length=255, verbose_name='Ism')),
                ('middleName', models.CharField(max_length=255, verbose_name='Sharif')),
                ('lastName', models.CharField(max_length=255, verbose_name='Familiya')),
                ('position', models.CharField(max_length=255, verbose_name='Lavozim')),
                ('department', models.CharField(max_length=255, verbose_name="Bo'lim")),
                ('phone', models.CharField(max_length=100, verbose_name='Telefon')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('hours', models.CharField(max_length=255, verbose_name='Qabul vaqti')),
                ('biography', models.TextField(verbose_name='Biografiya')),
                ('image', models.ImageField(upload_to='management/', verbose_name='Rasm')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Rahbar',
                'verbose_name_plural': 'Rahbarlar',
                'ordering': ['order', 'group_id'],
            },
        ),
    ]
