# Generated by Django 5.2.4 on 2025-07-28 10:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_statisticdata_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Author (en)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Автор (ru)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Comment (en)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий (ru)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.news', verbose_name='Yangilik / Новость / News'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt / Время создания / Created At'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchistatistika',
            name='jami_kirishlar',
            field=models.PositiveIntegerField(default=0, verbose_name='Jami kirishlar / Всего входов / Total Logins'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchistatistika',
            name='oxirgi_faollik',
            field=models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilanish / Последнее обновление / Last Update'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='ageRange',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Yosh oralig‘i / Возраст / Age Range'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='benefits_en',
            field=models.TextField(blank=True, null=True, verbose_name='Benefits (en)'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='benefits_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Преимущества (ru)'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan / Кем создано / Created By'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='requirements_en',
            field=models.TextField(blank=True, null=True, verbose_name='Requirements (en)'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='requirements_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Требования (ru)'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (en)'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (ru)'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqt / Дата добавления / Created At'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='message_en',
            field=models.TextField(blank=True, null=True, verbose_name='Message (en)'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='message_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение (ru)'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (en)'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя (ru)'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon / Телефон / Phone'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category (en)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория (ru)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Short description (en)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание (ru)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='fullContent_en',
            field=models.TextField(blank=True, null=True, verbose_name='Full text (en)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='fullContent_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Полный текст (ru)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_news', to=settings.AUTH_USER_MODEL, verbose_name='Layklar / Лайки / Likes'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publishedAt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='E’lon qilingan vaqt / Дата публикации / Published At'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (en)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (ru)'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Rasm / Фото / Image'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.news', verbose_name='Yangilik / Новость / News'),
        ),
        migrations.AlterField(
            model_name='sessiyaizlovi',
            name='oxirgi_harakat',
            field=models.DateTimeField(auto_now=True, verbose_name='Oxirgi harakat / Последнее действие / Last Activity'),
        ),
        migrations.AlterField(
            model_name='sessiyaizlovi',
            name='sessiya_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Sessiya ID'),
        ),
        migrations.AlterField(
            model_name='statisticdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqt / Дата добавления / Created At'),
        ),
        migrations.AlterField(
            model_name='statisticdata',
            name='month',
            field=models.CharField(choices=[('Yanvar', 'Yanvar'), ('Fevral', 'Fevral'), ('Mart', 'Mart'), ('Aprel', 'Aprel'), ('May', 'May'), ('Iyun', 'Iyun'), ('Iyul', 'Iyul'), ('Avgust', 'Avgust'), ('Sentyabr', 'Sentyabr'), ('Oktyabr', 'Oktyabr'), ('Noyabr', 'Noyabr'), ('Dekabr', 'Dekabr')], default='Yanvar', max_length=20, verbose_name='Oy / Месяц / Month'),
        ),
        migrations.AlterField(
            model_name='statisticdata',
            name='station_name',
            field=models.CharField(choices=[('Beruniy', 'Beruniy'), ('Tinchlik', 'Tinchlik'), ('Chorsu', 'Chorsu'), ('Gʻafur Gʻulom', 'Gʻafur Gʻulom'), ('Alisher Navoiy', 'Alisher Navoiy'), ('Abdulla Qodiriy', 'Abdulla Qodiriy'), ('Pushkin', 'Pushkin'), ('Buyuk Ipak Yoʻli', 'Buyuk Ipak Yoʻli'), ('Novza', 'Novza'), ('Milliy bogʻ', 'Milliy bogʻ'), ('Xalqlar doʻstligi', 'Xalqlar doʻstligi'), ('Chilonzor', 'Chilonzor'), ('Mirzo Ulugʻbek', 'Mirzo Ulugʻbek'), ('Olmazor', 'Olmazor'), ('Doʻstlik', 'Doʻstlik'), ('Mashinasozlar', 'Mashinasozlar'), ('Toshkent', 'Toshkent'), ('Oybek', 'Oybek'), ('Kosmonavtlar', 'Kosmonavtlar'), ('Oʻzbekiston', 'Oʻzbekiston'), ('Hamid Olimjon', 'Hamid Olimjon'), ('Ming Oʻrik', 'Ming Oʻrik'), ('Yunus Rajabiy', 'Yunus Rajabiy'), ('Shahriston', 'Shahriston'), ('Bodomzor', 'Bodomzor'), ('Minor', 'Minor'), ('Turkiston', 'Turkiston'), ('Yunusobod', 'Yunusobod'), ('Tuzel', 'Tuzel'), ('Yashnobod', 'Yashnobod'), ('Texnopark', 'Texnopark'), ('Sergeli', 'Sergeli'), ('Choshtepa', 'Choshtepa'), ('Turon', 'Turon'), ('Chinor', 'Chinor'), ('Yangiobod', 'Yangiobod'), ('Rohat', 'Rohat'), ('Oʻzgarish', 'Oʻzgarish'), ('Yangihayot', 'Yangihayot'), ('Qoʻyliq', 'Qoʻyliq'), ('Matonat', 'Matonat'), ('Qiyot', 'Qiyot'), ('Tolariq', 'Tolariq'), ('Xonobod', 'Xonobod'), ('Quruvchilar', 'Quruvchilar'), ('Olmos', 'Olmos'), ('Paxtakor', 'Paxtakor'), ('Qipchoq', 'Qipchoq'), ('Amir Temur xiyoboni', 'Amir Temur xiyoboni'), ('Mustaqillik maydoni', 'Mustaqillik maydoni')], max_length=100, verbose_name='Bekat / Станция / Station'),
        ),
        migrations.AlterField(
            model_name='statisticdata',
            name='user_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Foydalanuvchilar soni / Кол-во пользователей / Users Count'),
        ),
    ]
