# Generated by Django 5.2.4 on 2026-01-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', 'Uz'), ('ru', 'Ru'), ('en', 'En')], default='uz', max_length=2, verbose_name='Til')),
                ('group_id', models.PositiveIntegerField(verbose_name='Guruh ID')),
                ('title', models.CharField(max_length=255, verbose_name="Bo'lim nomi")),
                ('head', models.CharField(max_length=255, verbose_name='Rahbar')),
                ('schedule', models.CharField(max_length=255, verbose_name='Ish tartibi')),
                ('reception', models.CharField(max_length=255, verbose_name='Qabul vaqti')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('image', models.ImageField(upload_to='departments/', verbose_name='Rasm')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
                'ordering': ['order', 'group_id'],
            },
        ),
    ]
