# Generated by Django 5.2.4 on 2025-07-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_comment_author_en_alter_comment_author_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foydalanuvchistatistika',
            name='jami_kirishlar',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='foydalanuvchistatistika',
            name='oxirgi_faollik',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sessiyaizlovi',
            name='oxirgi_harakat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sessiyaizlovi',
            name='sessiya_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
