# Generated by Django 5.2.4 on 2026-01-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaphoto',
            options={'ordering': ['order', 'group_id'], 'verbose_name': 'Media Foto', 'verbose_name_plural': 'Media Fotolar'},
        ),
        migrations.AlterModelOptions(
            name='mediavideo',
            options={'ordering': ['order', 'group_id'], 'verbose_name': 'Media Video', 'verbose_name_plural': 'Media Videolar'},
        ),
        migrations.RemoveField(
            model_name='mediaphoto',
            name='category_key',
        ),
        migrations.RemoveField(
            model_name='mediaphoto',
            name='title_key',
        ),
        migrations.RemoveField(
            model_name='mediavideo',
            name='category_key',
        ),
        migrations.RemoveField(
            model_name='mediavideo',
            name='title_key',
        ),
        migrations.AddField(
            model_name='mediaphoto',
            name='category',
            field=models.CharField(default=1, max_length=100, verbose_name='Kategoriya'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaphoto',
            name='group_id',
            field=models.PositiveIntegerField(default=1, verbose_name='Guruh ID (Bir xil rasm uchun)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaphoto',
            name='language',
            field=models.CharField(choices=[('uz', 'Uz'), ('ru', 'Ru'), ('en', 'En')], default='uz', max_length=2),
        ),
        migrations.AddField(
            model_name='mediaphoto',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Sarlavha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediavideo',
            name='category',
            field=models.CharField(default=1, max_length=100, verbose_name='Kategoriya'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediavideo',
            name='group_id',
            field=models.PositiveIntegerField(default=1, verbose_name='Guruh ID (Bir xil video uchun)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediavideo',
            name='language',
            field=models.CharField(choices=[('uz', 'Uz'), ('ru', 'Ru'), ('en', 'En')], default='uz', max_length=2),
        ),
        migrations.AddField(
            model_name='mediavideo',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Sarlavha'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediavideo',
            name='video_url',
            field=models.URLField(help_text='YouTube embed URL'),
        ),
        migrations.AlterField(
            model_name='mediavideo',
            name='views',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
