# Generated by Django 5.2.4 on 2025-07-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_foydalanuvchistatistika_jami_kirishlar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='likes',
        ),
        migrations.AddField(
            model_name='news',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes soni'),
        ),
    ]
