# Generated by Django 5.2.4 on 2025-07-29 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_news_likes_news_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='likes_count',
        ),
    ]
