# Generated by Django 5.2.4 on 2025-07-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_news_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes soni'),
        ),
    ]
