# Generated by Django 5.2.4 on 2025-07-30 04:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_news_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='category_uz',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='news',
            name='fullContent_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='fullContent_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='fullContent_uz',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_uz',
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='news',
            name='fullContent',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='news',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='publishedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
