# Generated by Django 5.2.4 on 2025-07-30 04:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_news_category_en_remove_news_category_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='fullContent',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.AddField(
            model_name='news',
            name='category_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category (en)'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория (ru)'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategoriya (uz)'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Short description (en)'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание (ru)'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Qisqa tavsif (uz)'),
        ),
        migrations.AddField(
            model_name='news',
            name='fullContent_en',
            field=models.TextField(blank=True, null=True, verbose_name='Full text (en)'),
        ),
        migrations.AddField(
            model_name='news',
            name='fullContent_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Полный текст (ru)'),
        ),
        migrations.AddField(
            model_name='news',
            name='fullContent_uz',
            field=models.TextField(blank=True, null=True, verbose_name='To‘liq matn (uz)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (en)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (ru)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sarlavha (uz)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes soni'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publishedAt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='E’lon qilingan vaqt / Дата публикации / Published At'),
        ),
    ]
