# Generated by Django 5.2.4 on 2025-07-31 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_news_category_remove_news_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobVacancyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ism (uz)')),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя (ru)')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (en)')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon / Телефон / Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('file', models.FileField(blank=True, null=True, upload_to='jobVacancyRequests/', verbose_name='Fayl / Файл / File')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqt / Дата добавления / Created At')),
                ('jobVacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='home.jobvacancy', verbose_name='Vakansiya / Вакансия / Job Vacancy')),
            ],
        ),
    ]
