# Generated by Django 5.2.4 on 2025-07-31 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_jobvacancyrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobvacancy',
            name='ageRange',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='benefits_en',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='benefits_ru',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='benefits_uz',
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='education_status_en',
            field=models.CharField(blank=True, choices=[('oliy', 'Higher'), ("o'rta", 'Secondary'), ("o'rta mahsus", 'Specialized secondary')], max_length=20, null=True, verbose_name="Ma'lumot (en)"),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='education_status_ru',
            field=models.CharField(blank=True, choices=[('oliy', 'Высшее'), ("o'rta", 'Среднее'), ("o'rta mahsus", 'Среднее специальное')], max_length=20, null=True, verbose_name="Ma'lumot (ru)"),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='education_status_uz',
            field=models.CharField(blank=True, choices=[('oliy', 'Oliy'), ("o'rta", "O'rta"), ("o'rta mahsus", "O'rta mahsus")], max_length=20, null=True, verbose_name="Ma'lumot (uz)"),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='mutaxasislik_en',
            field=models.TextField(blank=True, null=True, verbose_name='Mutaxasislik (en)'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='mutaxasislik_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Мутации (ru)'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='mutaxasislik_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Mutaxasislik (uz)'),
        ),
    ]
