# Generated by Django 5.2.4 on 2025-07-31 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_jobvacancy_agerange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancyrequest',
            name='status',
            field=models.CharField(choices=[('pending', "Ko'rilmoqda"), ('answered', 'Javob berilgan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='jobvacancyrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='jobvacancyrequest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='jobVacancyRequests/', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='jobvacancyrequest',
            name='jobVacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='home.jobvacancy', verbose_name='Vakansiya'),
        ),
        migrations.AlterField(
            model_name='jobvacancyrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
    ]
