# Generated by Django 5.2.4 on 2025-07-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_jobvacancyrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='answered_requests',
            field=models.PositiveIntegerField(default=0, verbose_name='Qabul qilinganlar'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='pending_requests',
            field=models.PositiveIntegerField(default=0, verbose_name='Ko‘rib chiqilayotganlar'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='rejected_requests',
            field=models.PositiveIntegerField(default=0, verbose_name='Rad etilganlar'),
        ),
    ]
