# Generated by Django 5.2.4 on 2025-07-31 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_jobvacancy_answered_requests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Bekat nomi')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='YouTube havolasi')),
            ],
        ),
        migrations.CreateModel(
            name='StationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stations/', verbose_name='Rasm')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.station', verbose_name='Bekat')),
            ],
        ),
    ]
