# Generated by Django 5.2.4 on 2025-07-31 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_station_stationimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='youtube_link',
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Bekat nomi'),
        ),
        migrations.AlterField(
            model_name='stationimage',
            name='image',
            field=models.ImageField(upload_to='stations/images/'),
        ),
        migrations.AlterField(
            model_name='stationimage',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.station'),
        ),
        migrations.CreateModel(
            name='StationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Video nomi')),
                ('url', models.URLField(verbose_name='YouTube URL')),
                ('thumbnail', models.URLField(blank=True, null=True, verbose_name='Video preview rasmi')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='home.station')),
            ],
        ),
    ]
