# Generated by Django 5.2.4 on 2025-07-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_station_youtube_link_alter_station_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationvideo',
            name='station',
        ),
        migrations.AddField(
            model_name='lostitemrequest',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address (en)'),
        ),
        migrations.AddField(
            model_name='lostitemrequest',
            name='address_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес (ru)'),
        ),
        migrations.AddField(
            model_name='lostitemrequest',
            name='address_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil (uz)'),
        ),
        migrations.AddField(
            model_name='lostitemrequest',
            name='passport',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Passport'),
        ),
        migrations.DeleteModel(
            name='StationImage',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.DeleteModel(
            name='StationVideo',
        ),
    ]
