# Generated by Django 5.2.4 on 2025-07-31 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_stationvideo_station_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lostitemrequest',
            old_name='address_uz',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='lostitemrequest',
            old_name='message_uz',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='lostitemrequest',
            old_name='name_uz',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='lostitemrequest',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='lostitemrequest',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='lostitemrequest',
            name='message_en',
        ),
        migrations.RemoveField(
            model_name='lostitemrequest',
            name='message_ru',
        ),
        migrations.RemoveField(
            model_name='lostitemrequest',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='lostitemrequest',
            name='name_ru',
        ),
    ]
