# Generated by Django 5.2.4 on 2025-08-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_rename_address_uz_lostitemrequest_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitemrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Javob berilmagan'), ('answered', 'Javob berilgan')], default='pending', max_length=10, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Xabar'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='lostitemrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
    ]
