# Generated by Django 5.2.4 on 2025-08-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_lostitemrequest_status_alter_lostitemrequest_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitemrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Javob berilmagan'), ('answered', 'Javob berilgan')], default='pending', max_length=10),
        ),
    ]
