# Generated by Django 5.2.4 on 2025-08-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_lostitemrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticdata',
            name='year',
            field=models.CharField(choices=[('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], default='2025', max_length=20, verbose_name='Yil / Год / Year'),
        ),
    ]
