# Generated by Django 5.2.4 on 2025-08-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_statisticdata_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id']},
        ),
    ]
