# Generated by Django 5.2.4 on 2025-08-19 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_statisticdata_station_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_uz',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content_uz',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='jobvacancyrequest',
            old_name='name_uz',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author_en',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author_ru',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='jobvacancyrequest',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='jobvacancyrequest',
            name='name_ru',
        ),
    ]
